# Generated by Django 4.2.1 on 2023-05-30 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        db_column="descrizionereparto",
                        help_text="Nome reparto",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "wards",
                "db_table": "reparti",
                "ordering": ["description"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        db_column="descrizionemansione",
                        help_text="Nome mansione",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fk_reparto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="human_resources.ward",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "roles",
                "db_table": "mansioni",
                "ordering": ["description"],
            },
        ),
        migrations.CreateModel(
            name="HumanResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cognomedipendente", models.CharField(max_length=50)),
                ("nomedipendente", models.CharField(max_length=50)),
                (
                    "immagine",
                    models.ImageField(
                        blank=True,
                        default="avataaars.png",
                        null=True,
                        upload_to="operator_pictures/",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("dataassunzione", models.DateField()),
                ("datadimissioni", models.DateField(blank=True, null=True)),
                ("qualifica", models.CharField(blank=True, max_length=50, null=True)),
                ("commenti", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fk_mansione",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="human_resources.role",
                    ),
                ),
                (
                    "fk_reparto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="human_resources.ward",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "dipendenti",
                "db_table": "dipendenti",
                "ordering": ["-dataassunzione"],
            },
        ),
    ]
