# Generated by Django 4.2.1 on 2023-06-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0004_alter_dettaglioregistroformazione_fk_registro_formazione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humanresource',
            name='immagine',
            field=models.ImageField(blank=True, default='images/avatar.png', null=True, upload_to='operator_pictures/'),
        ),
    ]
