# Generated by Django 4.2.1 on 2023-06-06 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('human_resources', '0007_alter_humanresource_immagine'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroOreLavoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], default=2023)),
                ('entry_month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=6)),
                ('ore_lavorabili', models.IntegerField(blank=True, null=True)),
                ('ore_lavorate', models.IntegerField(blank=True, null=True)),
                ('straordinari', models.IntegerField(blank=True, null=True)),
                ('ferie_permessi', models.IntegerField(blank=True, null=True)),
                ('permessi_speciali', models.IntegerField(blank=True, null=True)),
                ('maternità', models.IntegerField(blank=True, null=True)),
                ('infortunio', models.IntegerField(blank=True, null=True)),
                ('formazione', models.IntegerField(blank=True, null=True)),
                ('formazione_neoassunti', models.IntegerField(blank=True, null=True)),
                ('malattia', models.IntegerField(blank=True, null=True)),
                ('n_infortuni', models.IntegerField(blank=True, null=True)),
                ('n_infortuni_itinere', models.IntegerField(blank=True, null=True)),
                ('n_malattie_professionali', models.IntegerField(blank=True, null=True)),
                ('ore_malattie_professionali', models.IntegerField(blank=True, null=True)),
                ('permessi_non_retribuiti', models.IntegerField(blank=True, null=True)),
                ('assenze_ingiustificate', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registro_ore_lavorazione', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
