# Generated by Django 4.2.1 on 2023-06-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0008_registroorelavoro'),
    ]

    operations = [
        migrations.AddField(
            model_name='dettaglioregistroformazione',
            name='prossima_scadenza',
            field=models.DateField(blank=True, null=True),
        ),
    ]
