# Generated by Django 4.2.1 on 2023-06-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0009_dettaglioregistroformazione_prossima_scadenza'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentrodiLavoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(db_column='descrizionecentrodilavoro', help_text='Nome centro di lavoro', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'centridilavoro',
                'db_table': 'centrodilavoro',
                'ordering': ['description'],
            },
        ),
        migrations.AddField(
            model_name='dettaglioregistroformazione',
            name='ore',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
