# Generated by Django 4.2.1 on 2023-06-06 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0010_centrodilavoro_dettaglioregistroformazione_ore'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValutazioneOperatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valutazione', models.CharField(choices=[('nessuna', 'Nessuna Valutazione'), ('minimo', "Minimo. L'operatore richiede approfondita formazione."), ('medio', "Medio. L'operatore è competente ma richiede affiancamento a persona di competenza superiore"), ('migliore', "Migliore. L'operatore è sufficientemente competente."), ('massimo', "Massimo. L'operatore può fornire formazione ad altri operatori.")], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fk_centro_di_lavoro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resources.centrodilavoro')),
                ('fk_hr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resources.humanresource')),
            ],
        ),
    ]
