# Generated by Django 4.2.1 on 2023-06-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0011_valutazioneoperatore'),
    ]

    operations = [
        migrations.AddField(
            model_name='valutazioneoperatore',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
