# Generated by Django 4.2.1 on 2023-11-15 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0022_alter_registroorelavoro_entry_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaformazione',
            options={'ordering': ['descrizione'], 'verbose_name_plural': 'Aree Formazione'},
        ),
        migrations.AlterModelOptions(
            name='centrodilavoro',
            options={'ordering': ['description'], 'verbose_name_plural': 'Centri di lavoro'},
        ),
        migrations.AlterModelOptions(
            name='corsoformazione',
            options={'ordering': ['descrizione'], 'verbose_name_plural': 'Corsi Formazione'},
        ),
        migrations.AlterModelOptions(
            name='registroformazione',
            options={'ordering': ['-data_formazione'], 'verbose_name_plural': 'Registri Formazione'},
        ),
        migrations.AlterModelOptions(
            name='registroorelavoro',
            options={'ordering': ['-entry_year', '-entry_month'], 'verbose_name_plural': 'Registri Ore Lavoro'},
        ),
        migrations.AlterModelOptions(
            name='valutazioneoperatore',
            options={'ordering': ['fk_hr'], 'verbose_name_plural': 'Valutazioni Operatori'},
        ),
    ]
