# Generated by Django 4.2.1 on 2023-05-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(default="default.jpg", upload_to="profile_pics"),
        ),
    ]
