# Generated by Django 4.2.1 on 2023-06-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_profile_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(default="avatar.png", upload_to="profile_pics"),
        ),
    ]
