# Generated by Django 4.2.1 on 2025-11-30 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_alter_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome Azienda')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('vat_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Partita IVA')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Indirizzo')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Città')),
                ('country', models.CharField(default='IT', max_length=100, verbose_name='Paese')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attiva')),
                ('subscription_plan', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=50, verbose_name='Piano Subscription')),
                ('subscription_expires', models.DateField(blank=True, null=True, verbose_name='Scadenza Subscription')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Azienda',
                'verbose_name_plural': 'Aziende',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profilo Utente', 'verbose_name_plural': 'Profili Utenti'},
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reparto'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono'),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Amministratore'), ('manager', 'Manager'), ('user', 'Utente'), ('viewer', 'Visualizzatore')], default='user', max_length=20, verbose_name='Ruolo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar.png', upload_to='profile_pics', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.company', verbose_name='Azienda'),
        ),
    ]
