# Generated by Django 4.2.1 on 2025-11-30 21:35

from django.db import migrations


def create_default_company(apps, schema_editor):
    """
    Create a default company and assign it to all existing profiles.
    This is a one-time data migration for multi-tenant conversion.
    """
    Company = apps.get_model('accounts', 'Company')
    Profile = apps.get_model('accounts', 'Profile')

    # Create default company if it doesn't exist
    # TODO: Replace 'Your Company Name' with your actual company name before production deploy
    default_company, created = Company.objects.get_or_create(
        slug='default-company',
        defaults={
            'name': 'Your Company Name',  # ⚠️ CHANGE THIS to your company name
            'is_active': True,
            'subscription_plan': 'enterprise',  # Set appropriate plan
            'country': 'IT'
        }
    )

    if created:
        print(f"✓ Created default company: {default_company.name}")
    else:
        print(f"✓ Default company already exists: {default_company.name}")

    # Assign default company to all existing profiles without a company
    profiles_updated = Profile.objects.filter(company__isnull=True).update(
        company=default_company,
        role='admin'  # First users become admins of their company
    )

    print(f"✓ Updated {profiles_updated} profiles with default company")


def reverse_migration(apps, schema_editor):
    """
    Reverse operation - set all profiles company to null
    """
    Profile = apps.get_model('accounts', 'Profile')
    Profile.objects.all().update(company=None)

    # Optionally delete the default company
    Company = apps.get_model('accounts', 'Company')
    Company.objects.filter(slug='default-company').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_company_alter_profile_options_profile_created_at_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_company, reverse_migration),
    ]
