# Generated by Django 4.2.1 on 2023-06-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizzazioni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dettaglioscadenzaautorizzazione',
            name='n_rinnovo',
            field=models.CharField(default='prova', help_text='numero autorizzazione', max_length=100),
            preserve_default=False,
        ),
    ]
