# Generated by Django 4.2.1 on 2023-06-20 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autorizzazioni', '0002_alter_dettaglioscadenzaautorizzazione_n_rinnovo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroAutorizzazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(help_text='descrizione', max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parametro_autorizzazione', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['descrizione'],
            },
        ),
    ]
