# Generated by Django 4.2.1 on 2023-06-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutenzioni', '0003_manutenzioneordinaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='attrezzatura',
            name='data_dismissione',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attrezzatura',
            name='is_dismesso',
            field=models.BooleanField(default=False),
        ),
    ]
