# Generated by Django 4.2.1 on 2023-06-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutenzioni', '0004_attrezzatura_data_dismissione_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attrezzatura',
            name='periodo_taratura',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
