# Generated by Django 4.2.1 on 2023-07-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutenzioni', '0007_attrezzatura_fk_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutenzionestraordinaria',
            name='data_fattura',
            field=models.DateField(blank=True, null=True),
        ),
    ]
