# Generated by Django 4.2.1 on 2023-10-23 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manutenzioni', '0010_attrezzatura_fk_human_resources'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attrezzatura',
            old_name='fk_human_resources',
            new_name='fk_human_resource',
        ),
    ]
