# Generated by Django 4.2.1 on 2023-10-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutenzioni', '0011_rename_fk_human_resources_attrezzatura_fk_human_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='attrezzatura',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tools_images'),
        ),
    ]
