# Generated by Django 4.2.1 on 2024-03-20 15:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ricette.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acquistopelli', '0009_lotto_fk_macello'),
        ('chem_man', '0023_alter_prodottochimico_options'),
        ('articoli', '0018_caratteristicaprocedura_numero_riga'),
    ]

    operations = [
        migrations.CreateModel(
            name='RicettaBagnato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ricetta', models.IntegerField(default=None)),
                ('data_ricetta', models.DateField(default=datetime.date.today)),
                ('numero_revisione', models.IntegerField(blank=True, null=True)),
                ('data_revisione', models.DateField(default=datetime.date.today)),
                ('kg_ricetta', models.DecimalField(decimal_places=0, max_digits=4)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ricette_bagnato', to=settings.AUTH_USER_MODEL)),
                ('fk_articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ricette_bagnato', to='articoli.articolo')),
                ('fk_tipoanimale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ricette_bagnato', to='acquistopelli.tipoanimale')),
                ('fk_tipogrezzo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ricette_bagnato', to='acquistopelli.tipogrezzo')),
            ],
            options={
                'ordering': ['-data_ricetta'],
            },
        ),
        migrations.CreateModel(
            name='RicettaRifinizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ricetta', models.IntegerField(blank=True, null=True)),
                ('data_ricetta', models.DateField(default=datetime.date.today)),
                ('numero_revisione', models.IntegerField(blank=True, null=True)),
                ('data_revisione', models.DateField(default=datetime.date.today)),
                ('ricetta_per_pelli', models.DecimalField(decimal_places=0, max_digits=4)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ricette_rifinizione', to=settings.AUTH_USER_MODEL)),
                ('fk_articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ricette_rifinizione', to='articoli.articolo')),
            ],
            options={
                'ordering': ['-data_ricetta'],
            },
        ),
        migrations.CreateModel(
            name='RicettaColoreRifinizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ricetta', models.IntegerField(blank=True, null=True)),
                ('data_ricetta', models.DateField(default=datetime.date.today)),
                ('numero_revisione', models.IntegerField(blank=True, null=True)),
                ('data_revisione', models.DateField(default=datetime.date.today)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ricette_colore_rifinizione', to=settings.AUTH_USER_MODEL)),
                ('fk_articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ricette_colore_rifinizione', to='articoli.articolo')),
                ('fk_colore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ricette_colore_rifinizione', to='articoli.colore')),
            ],
            options={
                'ordering': ['-data_ricetta'],
            },
        ),
        migrations.CreateModel(
            name='RicettaColoreBagnato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ricetta', models.IntegerField(default=None)),
                ('data_ricetta', models.DateField(default=datetime.date.today)),
                ('numero_revisione', models.IntegerField(blank=True, null=True)),
                ('data_revisione', models.DateField(default=datetime.date.today)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ricette_colore_bagnato', to=settings.AUTH_USER_MODEL)),
                ('fk_articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ricette_colore_bagnato', to='articoli.articolo')),
                ('fk_colore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ricette_colore_bagnato', to='articoli.colore')),
                ('fk_ricetta_bagnato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ricette_colore_bagnato', to='ricette.ricettabagnato')),
            ],
            options={
                'ordering': ['-data_ricetta'],
            },
        ),
        migrations.CreateModel(
            name='OperazioneRicette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=100)),
                ('ward_ref', models.CharField(choices=[('Bagnato', 'Bagnato'), ('Rifinizione', 'Rifinizione')], max_length=11)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operazione_ricette', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['descrizione'],
            },
        ),
        migrations.CreateModel(
            name='DettaglioRicettaRifinizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_riga', models.IntegerField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=8)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dettaglio_ricette_rifinizione', to=settings.AUTH_USER_MODEL)),
                ('fk_operazione_ricette', models.ForeignKey(limit_choices_to=ricette.models.DettaglioRicettaRifinizione.get_choices_operations, on_delete=django.db.models.deletion.CASCADE, related_name='dettaglio_ricette_rifinizione', to='ricette.operazionericette')),
                ('fk_prodotto_chimico', models.ForeignKey(limit_choices_to=ricette.models.DettaglioRicettaRifinizione.get_choices_chemical, on_delete=django.db.models.deletion.CASCADE, related_name='dettaglio_ricette_rifinizione', to='chem_man.prodottochimico')),
                ('fk_ricetta_rifinizione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettaglio_ricette_rifinizione', to='ricette.ricettarifinizione')),
            ],
            options={
                'ordering': ['numero_riga'],
            },
        ),
        migrations.CreateModel(
            name='DettaglioRicettaColoreRifinizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_riga', models.IntegerField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=8)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dettaglio_colore_rifinizione', to=settings.AUTH_USER_MODEL)),
                ('fk_operazione_ricette', models.ForeignKey(limit_choices_to=ricette.models.DettaglioRicettaColoreRifinizione.get_choices_operations, on_delete=django.db.models.deletion.CASCADE, related_name='dettaglio_colore_rifinizione', to='ricette.operazionericette')),
                ('fk_prodotto_chimico', models.ForeignKey(limit_choices_to=ricette.models.DettaglioRicettaColoreRifinizione.get_choices_chemical, on_delete=django.db.models.deletion.CASCADE, related_name='dettaglio_colore_rifinizione', to='chem_man.prodottochimico')),
                ('fk_ricetta_colore_rifinizione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettaglio_colore_rifinizione', to='ricette.ricettacolorerifinizione')),
            ],
            options={
                'ordering': ['numero_riga'],
            },
        ),
        migrations.CreateModel(
            name='DettaglioRicettaBagnato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_riga', models.IntegerField()),
                ('temperatura', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=8)),
                ('tempo', models.CharField(blank=True, max_length=50, null=True)),
                ('procedura', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dettaglio_ricette_bagnato', to=settings.AUTH_USER_MODEL)),
                ('fk_operazione_ricette', models.ForeignKey(limit_choices_to=ricette.models.DettaglioRicettaBagnato.get_choices_operations, on_delete=django.db.models.deletion.CASCADE, related_name='dettaglio_ricette_bagnato', to='ricette.operazionericette')),
                ('fk_prodotto_chimico', models.ForeignKey(limit_choices_to=ricette.models.DettaglioRicettaBagnato.get_choices_chemical, on_delete=django.db.models.deletion.CASCADE, related_name='dettaglio_ricette_bagnato', to='chem_man.prodottochimico')),
                ('fk_ricetta_bagnato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettaglio_ricette_bagnato', to='ricette.ricettabagnato')),
            ],
            options={
                'ordering': ['numero_riga'],
            },
        ),
    ]
