# Generated by Django 4.2.1 on 2023-09-13 18:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "acquistopelli",
            "0005_alter_lotto_fk_fornitore_alter_lotto_fk_tipoanimale_and_more",
        ),
        ("articoli", "0004_articolo_fk_tipoanimale_articolo_fk_tipogrezzo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperazioneRicette",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descrizone", models.CharField(max_length=100)),
                (
                    "ward_ref",
                    models.CharField(
                        choices=[
                            ("Bagnato", "Bagnato"),
                            ("Rifinizione", "Rifinizione"),
                        ],
                        max_length=11,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RicettaBagnato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_ricetta", models.IntegerField(default=None)),
                ("data_ricetta", models.DateField(default=datetime.date.today)),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ricette_bagnato",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fk_articolo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ricette_bagnato",
                        to="articoli.articolo",
                    ),
                ),
                (
                    "fk_tipoanimale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ricette_bagnato",
                        to="acquistopelli.tipoanimale",
                    ),
                ),
                (
                    "fk_tipogrezzo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ricette_bagnato",
                        to="acquistopelli.tipogrezzo",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_ricetta"],
            },
        ),
        migrations.CreateModel(
            name="RicettaRifinizione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RicettaFondo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_ricetta", models.IntegerField(default=None)),
                ("data_ricetta", models.DateField(default=datetime.date.today)),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ricette_fondo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fk_colore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ricette_fondo",
                        to="articoli.colore",
                    ),
                ),
                (
                    "fk_ricetta_bagnato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ricette_fondo",
                        to="ricette.ricettabagnato",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_ricetta"],
            },
        ),
        migrations.CreateModel(
            name="RevisioneRicettaFondo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_revisione", models.IntegerField(default=None)),
                ("data_revisione", models.DateField(default=datetime.date.today)),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisione_ricette_fondo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fk_ricetta_fondo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisione_ricette_fondo",
                        to="ricette.ricettafondo",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_revisione"],
            },
        ),
        migrations.CreateModel(
            name="RevisioneRicettaBagnato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_revisione", models.IntegerField(default=None)),
                ("data_revisione", models.DateField(default=datetime.date.today)),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisione_ricette_bagnato",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fk_ricetta_bagnato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisione_ricette_bagnato",
                        to="ricette.ricettabagnato",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_revisione"],
            },
        ),
    ]
