# Generated by Django 4.2.1 on 2023-09-13 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ricette.models


class Migration(migrations.Migration):

    dependencies = [
        ("chem_man", "0019_delete_operazionericette_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ricette", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ricettabagnato",
            name="kg_ricetta",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="DettaglioRevisioneRicettaFondo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_riga", models.IntegerField()),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=8)),
                ("temperatura", models.CharField(max_length=50)),
                ("tempo", models.CharField(max_length=50)),
                ("procedura", models.CharField(max_length=100)),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dettaglio_revisione_ricette_fondo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fk_operazione_ricette",
                    models.ForeignKey(
                        limit_choices_to=ricette.models.DettaglioRevisioneRicettaFondo.get_choices,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dettaglio_revisione_ricette_fondo",
                        to="ricette.operazionericette",
                    ),
                ),
                (
                    "fk_prodotto_chimico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dettaglio_revisione_ricette_fondo",
                        to="chem_man.prodottochimico",
                    ),
                ),
                (
                    "fk_revisione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dettaglio_revisione_ricette_fondo",
                        to="ricette.revisionericettafondo",
                    ),
                ),
            ],
            options={
                "ordering": ["numero_riga"],
            },
        ),
        migrations.CreateModel(
            name="DettaglioRevisioneRicettaBagnato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_riga", models.IntegerField()),
                ("temperatura", models.CharField(max_length=50)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=8)),
                ("tempo", models.CharField(max_length=50)),
                ("procedura", models.CharField(max_length=100)),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dettaglio_revisione_ricette_bagnato",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fk_operazione_ricette",
                    models.ForeignKey(
                        limit_choices_to=ricette.models.DettaglioRevisioneRicettaBagnato.get_choices,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dettaglio_revisione_ricette_bagnato",
                        to="ricette.operazionericette",
                    ),
                ),
                (
                    "fk_prodotto_chimico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dettaglio_revisione_ricette_bagnato",
                        to="chem_man.prodottochimico",
                    ),
                ),
                (
                    "fk_revisione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dettaglio_revisione_ricette_bagnato",
                        to="ricette.revisionericettabagnato",
                    ),
                ),
            ],
            options={
                "ordering": ["numero_riga"],
            },
        ),
    ]
