# Generated by Django 4.2.1 on 2024-03-21 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ricette.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chem_man', '0023_alter_prodottochimico_options'),
        ('ricette', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DettaglioRicettaColoreBagnato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_riga', models.IntegerField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=8)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dettaglio_colore_bagnato', to=settings.AUTH_USER_MODEL)),
                ('fk_operazione_ricette', models.ForeignKey(limit_choices_to=ricette.models.DettaglioRicettaColoreBagnato.get_choices_operations, on_delete=django.db.models.deletion.CASCADE, related_name='dettaglio_colore_bagnato', to='ricette.operazionericette')),
                ('fk_prodotto_chimico', models.ForeignKey(limit_choices_to=ricette.models.DettaglioRicettaColoreBagnato.get_choices_chemical, on_delete=django.db.models.deletion.CASCADE, related_name='dettaglio_colore_bagnato', to='chem_man.prodottochimico')),
                ('fk_ricetta_colore_bagnato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettaglio_colore_bagnato', to='ricette.ricettacolorebagnato')),
            ],
            options={
                'ordering': ['numero_riga'],
            },
        ),
    ]
