# Generated by Django 4.2.1 on 2023-09-14 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ricette", "0002_ricettabagnato_kg_ricetta_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="operazionericette",
            old_name="descrizone",
            new_name="descrizione",
        ),
    ]
