# Generated by Django 4.2.1 on 2024-03-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ricette', '0002_dettaglioricettacolorebagnato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ricettacolorebagnato',
            name='fk_ricetta_bagnato',
        ),
    ]
