# Generated by Django 4.2.1 on 2024-03-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricette', '0003_remove_ricettacolorebagnato_fk_ricetta_bagnato'),
    ]

    operations = [
        migrations.AddField(
            model_name='dettaglioricettacolorebagnato',
            name='procedura',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dettaglioricettacolorebagnato',
            name='temperatura',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dettaglioricettacolorebagnato',
            name='tempo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
