# Generated by Django 4.2.1 on 2023-09-21 13:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ricette.models


class Migration(migrations.Migration):

    dependencies = [
        ('chem_man', '0019_delete_operazionericette_and_more'),
        ('articoli', '0004_articolo_fk_tipoanimale_articolo_fk_tipogrezzo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ricette', '0004_operazionericette_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ricettarifinizione',
            options={'ordering': ['-data_ricetta']},
        ),
        migrations.AddField(
            model_name='ricettarifinizione',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ricettarifinizione',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ricette_rifinizione', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ricettarifinizione',
            name='data_revisione',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='ricettarifinizione',
            name='data_ricetta',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='ricettarifinizione',
            name='fk_articolo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ricette_rifinizione', to='articoli.articolo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ricettarifinizione',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ricettarifinizione',
            name='numero_revisione',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ricettarifinizione',
            name='numero_ricetta',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ricettarifinizione',
            name='ricetta_per_pelli',
            field=models.DecimalField(decimal_places=0, default=100, max_digits=4),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DettaglioRicettaRifinizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_riga', models.IntegerField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fk_operazione_ricette', models.ForeignKey(limit_choices_to=ricette.models.DettaglioRicettaRifinizione.get_choices_operations, on_delete=django.db.models.deletion.CASCADE, related_name='dettaglio_ricette_rifinizione', to='ricette.operazionericette')),
                ('fk_prodotto_chimico', models.ForeignKey(limit_choices_to=ricette.models.DettaglioRicettaRifinizione.get_choices_chemical, on_delete=django.db.models.deletion.CASCADE, related_name='dettaglio_ricette_rifinizione', to='chem_man.prodottochimico')),
                ('fk_ricetta_rifinizione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettaglio_ricette_rifinizione', to='ricette.ricettarifinizione')),
            ],
            options={
                'ordering': ['numero_riga'],
            },
        ),
    ]
