# Generated by Django 4.2.1 on 2023-09-22 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ricette', '0005_alter_ricettarifinizione_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dettaglioricettarifinizione',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dettaglio_ricette_rifinizione', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dettaglioricettarifinizione',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
