# Generated by Django 4.2.1 on 2023-09-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricette', '0006_dettaglioricettarifinizione_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operazionericette',
            options={'ordering': ['descrizione']},
        ),
        migrations.AlterField(
            model_name='ricettarifinizione',
            name='numero_revisione',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ricettarifinizione',
            name='numero_ricetta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
