# Generated by Django 4.2.1 on 2024-02-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricette', '0007_alter_operazionericette_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dettaglioricettarifinizione',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
    ]
