# Generated by Django 4.2.1 on 2024-02-27 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ricette', '0009_dettaglioricettarifinizione_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ricettabagnato',
            name='data_revisione',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='ricettabagnato',
            name='numero_revisione',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
