# Generated by Django 4.2.1 on 2024-02-27 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ricette.models


class Migration(migrations.Migration):

    dependencies = [
        ("chem_man", "0023_alter_prodottochimico_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ricette", "0010_ricettabagnato_data_revisione_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DettaglioRicettaBagnato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_riga", models.IntegerField()),
                ("temperatura", models.CharField(max_length=50)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=8)),
                ("tempo", models.CharField(max_length=50)),
                ("procedura", models.CharField(max_length=100)),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dettaglio_ricette_bagnato",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fk_operazione_ricette",
                    models.ForeignKey(
                        limit_choices_to=ricette.models.DettaglioRicettaBagnato.get_choices,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dettaglio_ricette_bagnato",
                        to="ricette.operazionericette",
                    ),
                ),
                (
                    "fk_prodotto_chimico",
                    models.ForeignKey(
                        limit_choices_to=ricette.models.DettaglioRicettaBagnato.get_choices_chemical,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dettaglio_ricette_bagnato",
                        to="chem_man.prodottochimico",
                    ),
                ),
                (
                    "fk_ricetta_bagnato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dettaglio_ricette_bagnato",
                        to="ricette.ricettabagnato",
                    ),
                ),
            ],
            options={
                "ordering": ["numero_riga"],
            },
        ),
    ]
