# Generated by Django 4.2.1 on 2024-03-20 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ricette', '0012_alter_ricettacolorebagnato_created_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RicettaColoreBagnato',
        ),
    ]
