# Generated by Django 4.2.1 on 2023-06-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoraggi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatiProduzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inserimento', models.DateField()),
                ('industries_served', models.CharField(choices=[('apparel/clothing', 'Apparel/clothing'), ('automotive', 'Automotive'), ('contract', 'Contract'), ('footwear', 'Footwear'), ('footwear (athletic)', 'Footwear (Athletic)'), ('leather goods', 'Leather goods'), ('upholstery', 'Upholstery')], max_length=50)),
                ('n_pelli', models.IntegerField()),
                ('mq', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
            options={
                'ordering': ['-data_inserimento'],
            },
        ),
        migrations.AlterModelOptions(
            name='monitoraggioacqua',
            options={'ordering': ['-data_lettura']},
        ),
        migrations.AlterModelOptions(
            name='monitoraggioenergiaelettrica',
            options={'ordering': ['-data_lettura']},
        ),
        migrations.AlterModelOptions(
            name='monitoraggiogas',
            options={'ordering': ['-data_lettura']},
        ),
        migrations.RenameField(
            model_name='monitoraggioenergiaelettrica',
            old_name='Kwh_in',
            new_name='kwh_in',
        ),
    ]
