# Generated by Django 4.2.1 on 2023-06-13 15:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoraggi', '0003_datiproduzione_created_at_datiproduzione_created_by_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DatiProduzione',
            new_name='DatoProduzione',
        ),
    ]
