# Generated by Django 4.2.1 on 2023-06-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoraggi', '0004_rename_datiproduzione_datoproduzione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoraggioenergiaelettrica',
            name='kwh_in',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='monitoraggiogas',
            name='mc_in',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
