version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: qms-backend
    volumes:
      - ./backend:/app
      - ./backend/logs:/app/logs
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: qms-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

  
  nginx:
    image: nginx:stable
    container_name: qms-nginx
    depends_on:
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/staticfiles  # stesso volume condiviso con backend

volumes:
  static_volume: