# Generated by Django 4.2.1 on 2023-05-29 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0004_fornitore_is_lwg_lwgfornitore'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='XrTransferValueLwgFornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('fk_lwgfornitore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anagrafiche.lwgfornitore')),
                ('fk_transfervalue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anagrafiche.transfervalue')),
            ],
        ),
    ]
