# Generated by Django 4.2.1 on 2023-05-30 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafiche", "0005_transfervalue_xrtransfervaluelwgfornitore"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transfervalue",
            options={"ordering": ["description"]},
        ),
    ]
