# Generated by Django 4.2.1 on 2023-06-21 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("anagrafiche", "0006_alter_transfervalue_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fornitore",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fornitori",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
