# Generated by Django 4.2.1 on 2023-07-25 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0008_fornitore_pelli_fornitore_pc_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fornitore_Lavorazioni_Esterne',
            new_name='FornitoreLavorazioniEsterne',
        ),
        migrations.RenameModel(
            old_name='Fornitore_Pelli',
            new_name='FornitorePelli',
        ),
        migrations.RenameModel(
            old_name='Fornitore_PC',
            new_name='FornitoreProdottiChimici',
        ),
        migrations.RenameModel(
            old_name='Fornitore_Lavorazioni_Servizi',
            new_name='FornitoreServizi',
        ),
    ]
