# Generated by Django 4.2.1 on 2023-07-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0011_fornitorelavorazioniesterne_is_lwg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fornitorepelli',
            old_name='prova',
            new_name='urn',
        ),
        migrations.AddField(
            model_name='fornitore',
            name='sito_web',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fornitorepelli',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fornitorepelli',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fornitorepelli',
            name='tipo_fornitore',
            field=models.CharField(blank=True, choices=[('macello', 'Macello'), ('commerciante', 'Commerciante'), ('altro', 'Altro')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fornitore',
            name='categoria',
            field=models.CharField(choices=[('nessuna', 'Manca categoria'), ('pelli', 'Pelli'), ('prodotti chimici', 'Prodotti Chimici'), ('lavorazioni esterne', 'Lavorazioni Esterne'), ('servizi', 'Servizi'), ('manutenzioni', 'Manutenzioni')], default='nessuna', max_length=50),
        ),
    ]
