# Generated by Django 4.2.1 on 2023-08-01 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0012_rename_prova_fornitorepelli_urn_fornitore_sito_web_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornitorepelli',
            name='fornitore',
        ),
        migrations.RemoveField(
            model_name='fornitorepelli',
            name='id',
        ),
        migrations.RemoveField(
            model_name='fornitorepelli',
            name='is_lwg',
        ),
        migrations.AddField(
            model_name='fornitorepelli',
            name='fornitore_ptr',
            field=models.OneToOneField(auto_created=True, default=50, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='anagrafiche.fornitore'),
            preserve_default=False,
        ),
    ]
