# Generated by Django 4.2.1 on 2023-08-01 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0014_alter_fornitore_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornitorepelli',
            name='fornitore_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='fornitore_ptr_pelli', serialize=False, to='anagrafiche.fornitore'),
        ),
    ]
