# Generated by Django 4.2.1 on 2023-08-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafiche", "0015_alter_fornitorepelli_fornitore_ptr"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fornitore",
            name="is_lwg",
        ),
    ]
