# Generated by Django 4.2.1 on 2023-08-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafiche", "0016_remove_fornitore_is_lwg"),
    ]

    operations = [
        migrations.AddField(
            model_name="fornitorepelli",
            name="is_lwg",
            field=models.BooleanField(default=False),
        ),
    ]
