# Generated by Django 4.2.1 on 2023-08-04 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafiche", "0017_fornitorepelli_is_lwg"),
    ]

    operations = [
        migrations.CreateModel(
            name="FornitoreRifiuti",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fornitore_ptr",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        related_name="fornitore_ptr_rifiuti",
                        to="anagrafiche.fornitore",
                    ),
                ),
                ("prova", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="fornitorelavorazioniesterne",
            name="fornitore",
        ),
        migrations.RemoveField(
            model_name="fornitoreprodottichimici",
            name="fornitore",
        ),
        migrations.RemoveField(
            model_name="fornitoreservizi",
            name="fornitore",
        ),
        migrations.AddField(
            model_name="fornitorelavorazioniesterne",
            name="fornitore_ptr",
            field=models.OneToOneField(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                related_name="fornitore_ptr_lavorazioniesterne",
                to="anagrafiche.fornitore",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fornitoreprodottichimici",
            name="fornitore_ptr",
            field=models.OneToOneField(
                default=4,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                related_name="fornitore_ptr_prodottichimici",
                to="anagrafiche.fornitore",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fornitoreservizi",
            name="fornitore_ptr",
            field=models.OneToOneField(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                related_name="fornitore_ptr_servizi",
                to="anagrafiche.fornitore",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fornitore",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("nessuna", "Manca categoria"),
                    ("pelli", "Pelli"),
                    ("prodotti chimici", "Prodotti Chimici"),
                    ("lavorazioni esterne", "Lavorazioni Esterne"),
                    ("servizi", "Servizi"),
                    ("manutenzioni", "Manutenzioni"),
                    ("rifiuti", "Rifiuti"),
                ],
                default="nessuna",
                max_length=50,
            ),
        ),
    ]
