# Generated by Django 4.2.1 on 2023-12-13 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0024_detailfacilityauthorization_is_rinnovata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xrtransfervaluelwgfornitore',
            old_name='fk_lwgfornitore',
            new_name='fk_lwgcertificato',
        ),
    ]
