# Generated by Django 4.2.1 on 2023-12-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0026_xrtransfervaluelwgfornitore_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lwgfornitore',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='lwg_certificates/'),
        ),
    ]
