# Generated by Django 4.2.1 on 2023-12-15 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0028_alter_xrtransfervaluelwgfornitore_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilityauthorization',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='facilityauthorization',
            name='fk_facility',
        ),
        migrations.RemoveField(
            model_name='facilityauthorization',
            name='fk_fornitore',
        ),
        migrations.DeleteModel(
            name='DetailFacilityAuthorization',
        ),
        migrations.DeleteModel(
            name='FacilityAuthorization',
        ),
    ]
