# Generated by Django 4.2.1 on 2024-10-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0032_xrdocumentitrasportatore_xrdocumentismaltitore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrdocumentigestore',
            name='data_documento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xrdocumentigestore',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='xrdocumentismaltitore',
            name='data_documento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xrdocumentismaltitore',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='xrdocumentitrasportatore',
            name='data_documento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xrdocumentitrasportatore',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
