# Generated by Django 4.2.1 on 2024-10-07 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anagrafiche', '0034_remove_fornitorerifiuti_prova'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrdocumentigestore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xrdocumentigestore',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documenti_gestore', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='xrdocumentigestore',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
