# Generated by Django 4.2.1 on 2024-12-14 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0036_remove_fornitorerifiuti_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornitorerifiuti',
            name='id',
        ),
        migrations.AlterField(
            model_name='fornitorerifiuti',
            name='fornitore_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='fornitore_ptr_rifiuti', serialize=False, to='anagrafiche.fornitore'),
        ),
    ]
