# Generated by Django 4.2.1 on 2024-12-16 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0040_alter_xrtransfervaluelwgfornitore_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornitoreservizi',
            name='id',
        ),
        migrations.AlterField(
            model_name='fornitoreservizi',
            name='fornitore_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='fornitore_ptr_servizi', serialize=False, to='anagrafiche.fornitore'),
        ),
    ]
