# Generated by Django 4.2.1 on 2025-06-17 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0046_alter_xrdocumentigestore_fornitore_rifiuti_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornitoremacello',
            name='fornitore_ptr',
        ),
        migrations.RemoveField(
            model_name='fornitoremanutenzioni',
            name='fornitore_ptr',
        ),
        migrations.RemoveField(
            model_name='fornitorepelli',
            name='fornitore_ptr',
        ),
        migrations.RemoveField(
            model_name='fornitoreprodottichimici',
            name='fornitore_ptr',
        ),
        migrations.RemoveField(
            model_name='fornitorerifiuti',
            name='fornitore_ptr',
        ),
        migrations.RemoveField(
            model_name='fornitoreservizi',
            name='fornitore_ptr',
        ),
        migrations.DeleteModel(
            name='FornitoreLavorazioniEsterne',
        ),
        migrations.DeleteModel(
            name='FornitoreMacello',
        ),
        migrations.DeleteModel(
            name='FornitoreManutenzioni',
        ),
        migrations.DeleteModel(
            name='FornitorePelli',
        ),
        migrations.DeleteModel(
            name='FornitoreProdottiChimici',
        ),
        migrations.DeleteModel(
            name='FornitoreRifiuti',
        ),
        migrations.DeleteModel(
            name='FornitoreServizi',
        ),
    ]
