# Generated by Django 4.2.1 on 2025-11-30 16:43

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0051_alter_cliente_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornitore',
            name='country',
            field=django_countries.fields.CountryField(default='IT', max_length=2),
        ),
    ]
