# Generated by Django 4.2.1 on 2025-11-30 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_create_default_company'),
        ('anagrafiche', '0052_alter_fornitore_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='Azienda'),
        ),
        migrations.AddField(
            model_name='fornitore',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='Azienda'),
        ),
    ]
