# Generated by Django 4.2.1 on 2025-12-08 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_create_default_company'),
        ('anagrafiche', '0054_assign_default_company_to_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='Azienda'),
        ),
        migrations.AddField(
            model_name='facility',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facilitycontact',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='Azienda'),
        ),
        migrations.AddField(
            model_name='facilitycontact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='facilitycontact',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_contact_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lwgfornitore',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='Azienda'),
        ),
        migrations.AddField(
            model_name='lwgfornitore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='lwgfornitore',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lwg_fornitore_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='xrdocumentigestore',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='Azienda'),
        ),
        migrations.AddField(
            model_name='xrdocumentismaltitore',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='Azienda'),
        ),
        migrations.AddField(
            model_name='xrdocumentismaltitore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='xrdocumentismaltitore',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documenti_smaltitore_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='xrdocumentitrasportatore',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='Azienda'),
        ),
        migrations.AddField(
            model_name='xrdocumentitrasportatore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='xrdocumentitrasportatore',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documenti_trasportatore_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='xrtransfervaluelwgfornitore',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company', verbose_name='Azienda'),
        ),
    ]
