# Generated by Django 4.2.1 on 2025-12-08 19:52

from django.db import migrations


def assign_default_company(apps, schema_editor):
    """
    Assign default company to all anagrafiche records without a company
    """
    Company = apps.get_model('accounts', 'Company')
    Facility = apps.get_model('anagrafiche', 'Facility')
    FacilityContact = apps.get_model('anagrafiche', 'FacilityContact')
    LwgFornitore = apps.get_model('anagrafiche', 'LwgFornitore')
    XrDocumentiGestore = apps.get_model('anagrafiche', 'XrDocumentiGestore')
    XrDocumentiSmaltitore = apps.get_model('anagrafiche', 'XrDocumentiSmaltitore')
    XrDocumentiTrasportatore = apps.get_model('anagrafiche', 'XrDocumentiTrasportatore')
    XrTransferValueLwgFornitore = apps.get_model('anagrafiche', 'XrTransferValueLwgFornitore')

    # Get default company
    try:
        default_company = Company.objects.get(slug='default-company')
    except Company.DoesNotExist:
        print("⚠️  Default company not found! Skipping data migration.")
        return

    # Assign company to all records
    models_to_update = [
        ('Facility', Facility),
        ('FacilityContact', FacilityContact),
        ('LwgFornitore', LwgFornitore),
        ('XrDocumentiGestore', XrDocumentiGestore),
        ('XrDocumentiSmaltitore', XrDocumentiSmaltitore),
        ('XrDocumentiTrasportatore', XrDocumentiTrasportatore),
        ('XrTransferValueLwgFornitore', XrTransferValueLwgFornitore),
    ]

    for model_name, Model in models_to_update:
        updated = Model.objects.filter(company__isnull=True).update(company=default_company)
        print(f"✓ Updated {updated} {model_name} records with default company")


def reverse_migration(apps, schema_editor):
    """
    Reverse operation - set all company fields to null
    """
    Facility = apps.get_model('anagrafiche', 'Facility')
    FacilityContact = apps.get_model('anagrafiche', 'FacilityContact')
    LwgFornitore = apps.get_model('anagrafiche', 'LwgFornitore')
    XrDocumentiGestore = apps.get_model('anagrafiche', 'XrDocumentiGestore')
    XrDocumentiSmaltitore = apps.get_model('anagrafiche', 'XrDocumentiSmaltitore')
    XrDocumentiTrasportatore = apps.get_model('anagrafiche', 'XrDocumentiTrasportatore')
    XrTransferValueLwgFornitore = apps.get_model('anagrafiche', 'XrTransferValueLwgFornitore')

    Facility.objects.all().update(company=None)
    FacilityContact.objects.all().update(company=None)
    LwgFornitore.objects.all().update(company=None)
    XrDocumentiGestore.objects.all().update(company=None)
    XrDocumentiSmaltitore.objects.all().update(company=None)
    XrDocumentiTrasportatore.objects.all().update(company=None)
    XrTransferValueLwgFornitore.objects.all().update(company=None)


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0055_facility_company_facility_created_by_and_more'),
        ('accounts', '0008_create_default_company'),  # Ensure default company exists
    ]

    operations = [
        migrations.RunPython(assign_default_company, reverse_migration),
    ]
