# Generated by Django 4.2.1 on 2023-06-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionerifiuti", "0003_movimentorifiuti"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codicesmaltrec",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
