# Generated by Django 4.2.1 on 2023-10-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoraggi', '0005_alter_monitoraggioenergiaelettrica_kwh_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoraggioenergiaelettrica',
            name='kwh_in',
            field=models.DecimalField(decimal_places=3, max_digits=9),
        ),
    ]
