# Generated by Django 4.2.1 on 2023-11-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoraggi', '0006_alter_monitoraggioenergiaelettrica_kwh_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoproduzione',
            name='kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
    ]
