# Generated by Django 4.2.1 on 2024-01-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoraggi', '0007_datoproduzione_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoproduzione',
            name='industries_served',
            field=models.CharField(choices=[('apparel/clothing', 'Apparel/clothing'), ('aviation', 'Aviation'), ('automotive', 'Automotive'), ('contract', 'Contract'), ('footwear', 'Footwear'), ('footwear (athletic)', 'Footwear (Athletic)'), ('leather goods', 'Leather goods'), ('upholstery', 'Upholstery')], max_length=50),
        ),
    ]
