# Generated by Django 4.2.1 on 2024-01-24 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acquistopelli', '0005_alter_lotto_fk_fornitore_alter_lotto_fk_tipoanimale_and_more'),
        ('monitoraggi', '0008_alter_datoproduzione_industries_served'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoproduzione',
            name='fk_tipoanimale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dati_produzione', to='acquistopelli.tipoanimale'),
        ),
    ]
