# Generated by Django 4.2.1 on 2023-06-12 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manualeprocedure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificativo', models.CharField(max_length=50)),
                ('data_procedura', models.DateField()),
                ('descrizione', models.CharField(max_length=100)),
                ('is_eliminata', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedura', to=settings.AUTH_USER_MODEL)),
                ('fk_lwgsection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manualeprocedure.sezionelwg')),
            ],
        ),
    ]
