# Generated by Django 4.2.1 on 2023-06-12 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manualeprocedure', '0002_procedura'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisioneProcedura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_revisione', models.IntegerField()),
                ('data_revisione', models.DateField(default=django.utils.timezone.now)),
                ('documento', models.FileField(blank=True, null=True, upload_to='procedure/')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisione_procedura', to=settings.AUTH_USER_MODEL)),
                ('fk_procedura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manualeprocedure.procedura')),
            ],
            options={
                'ordering': ['-data_revisione'],
            },
        ),
        migrations.CreateModel(
            name='RevisioneModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_revisione', models.IntegerField()),
                ('data_revisione', models.DateField(default=django.utils.timezone.now)),
                ('documento', models.FileField(blank=True, null=True, upload_to='procedure/')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisione_modulo', to=settings.AUTH_USER_MODEL)),
                ('fk_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manualeprocedure.procedura')),
            ],
            options={
                'ordering': ['-data_revisione'],
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificativo', models.CharField(max_length=50)),
                ('data_modulo', models.DateField()),
                ('descrizione', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modulo', to=settings.AUTH_USER_MODEL)),
                ('fk_procedura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manualeprocedure.procedura')),
            ],
            options={
                'ordering': ['-data_modulo'],
            },
        ),
    ]
