# Generated by Django 4.2.1 on 2023-06-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonconformity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportonc',
            name='causa_radice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rapportonc',
            name='descrizione',
            field=models.TextField(blank=True, null=True),
        ),
    ]
