# Generated by Django 4.2.1 on 2023-06-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonconformity', '0004_processoaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='processoaudit',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
