# Generated by Django 4.2.1 on 2023-06-28 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nonconformity', '0007_alter_rapportonc_fk_rapportoaudit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processoaudit',
            old_name='fk_audit',
            new_name='fk_rapportoaudit',
        ),
    ]
