# Generated by Django 4.2.1 on 2023-06-13 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafiche", "0006_alter_transfervalue_options"),
        ("manutenzioni", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taratura",
            name="documento",
            field=models.FileField(blank=True, null=True, upload_to="tarature/"),
        ),
        migrations.AddField(
            model_name="taratura",
            name="fk_fornitore",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="anagrafiche.fornitore",
            ),
        ),
    ]
