# Generated by Django 4.2.1 on 2023-06-13 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafiche", "0006_alter_transfervalue_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("manutenzioni", "0002_taratura_documento_taratura_fk_fornitore"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManutenzioneOrdinaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_manutenzione", models.DateField()),
                ("descrizione", models.CharField(max_length=100)),
                ("is_eseguita", models.BooleanField(default=False)),
                ("prossima_scadenza", models.DateField()),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manutenzione_ordinaria",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fk_attrezzatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manutenzioni.attrezzatura",
                    ),
                ),
                (
                    "fk_fornitore",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="anagrafiche.fornitore",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_manutenzione"],
            },
        ),
    ]
