# Generated by Django 4.2.1 on 2023-06-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manutenzioni", "0005_alter_attrezzatura_periodo_taratura"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attrezzatura",
            name="modello",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="attrezzatura",
            name="serie_matricola",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
