# Generated by Django 4.2.1 on 2023-10-23 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('human_resources', '0021_alter_registroorelavoro_entry_month'),
        ('manutenzioni', '0008_alter_manutenzionestraordinaria_data_fattura'),
    ]

    operations = [
        migrations.AddField(
            model_name='attrezzatura',
            name='periodo_controlli_periodici',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attrezzatura',
            name='procedura_controlli_periodici',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attrezzatura',
            name='riferimento_normativo_controlli_periodici',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ControlloPeriodico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_controllo', models.DateField()),
                ('descrizione', models.CharField(max_length=100)),
                ('is_eseguita', models.BooleanField(default=False)),
                ('prossima_scadenza', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controllo_periodico', to=settings.AUTH_USER_MODEL)),
                ('fk_attrezzatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manutenzioni.attrezzatura')),
                ('fk_human_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resources.humanresource')),
            ],
            options={
                'ordering': ['-data_controllo'],
            },
        ),
    ]
