# Generated by Django 4.2.1 on 2023-10-23 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0021_alter_registroorelavoro_entry_month'),
        ('manutenzioni', '0009_attrezzatura_periodo_controlli_periodici_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attrezzatura',
            name='fk_human_resources',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resources.humanresource'),
        ),
    ]
