# Generated by Django 4.2.1 on 2025-05-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendite', '0003_alter_dettaglioordinecliente_fk_articolo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dettaglioordinecliente',
            name='completato',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dettaglioordinecliente',
            name='data_completamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dettaglioordinecliente',
            name='data_consegna',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dettaglioordinecliente',
            name='data_messa_in_lavoro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dettaglioordinecliente',
            name='in_lavorazione',
            field=models.BooleanField(default=False),
        ),
    ]
