# Generated by Django 4.2.1 on 2025-05-22 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articoli', '0022_listinocliente'),
        ('acquistopelli', '0010_sceltalotto_data_termine_and_more'),
        ('vendite', '0004_dettaglioordinecliente_completato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedaLavorazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_scheda', models.DateField(blank=True, null=True)),
                ('tot_pelli', models.PositiveIntegerField()),
                ('tot_pelli_finale', models.PositiveIntegerField()),
                ('metri_quadrati_finali', models.DecimalField(decimal_places=2, help_text='Inserisci la superficie in metri quadrati', max_digits=10, verbose_name='Superficie (m²)')),
                ('scheda_chiusa', models.BooleanField(default=False)),
                ('data_chiusura', models.DateField(blank=True, null=True, verbose_name='Data Chiusura Scheda')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheda_lavorazione', to=settings.AUTH_USER_MODEL)),
                ('fk_articolo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='scheda_lavorazione', to='articoli.articolo', verbose_name='Articolo')),
                ('fk_colore', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='scheda_lavorazione', to='articoli.colore', verbose_name='Colore')),
                ('fk_dettaglio_ordine_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheda_lavorazione', to='vendite.dettaglioordinecliente')),
            ],
            options={
                'verbose_name': 'Scheda lavorazione',
                'verbose_name_plural': 'Schede Lavorazione',
            },
        ),
        migrations.CreateModel(
            name='XRScelteSchede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xrscelteschede', to=settings.AUTH_USER_MODEL)),
                ('fk_sceltalotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xrscelteschede', to='acquistopelli.sceltalotto')),
                ('fk_schedalavorazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xrscelteschede', to='vendite.schedalavorazione')),
            ],
        ),
    ]
