# Generated by Django 4.2.1 on 2023-07-01 13:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("anagrafiche", "0007_alter_fornitore_created_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProdottoChimico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descrizione", models.CharField(max_length=100)),
                ("solvente", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "reparto",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bagnato", "Bagnato"),
                            ("rifinizione", "Rifinizione"),
                        ],
                        max_length=12,
                        null=True,
                    ),
                ),
                (
                    "flame_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "A - Liquidi molto infiammabili",
                                "A - Liquidi molto infiammabili",
                            ),
                            ("B - Liquidi infiammabili", "B - Liquidi infiammabili"),
                            ("C - Liquidi combustibili", "C - Liquidi combustibili"),
                            ("Non infiammabili", "Non infiammabili"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "zdhc_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("registered", "Registered"),
                            ("level 1", "Level 1"),
                            ("level 2", "Level 2"),
                            ("level 3", "Level 3"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prodotto_chimico",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fk_fornitore",
                    models.ForeignKey(
                        limit_choices_to={"categoria": "prodotti chimici"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prodotto_chimico",
                        to="anagrafiche.fornitore",
                    ),
                ),
            ],
            options={
                "ordering": ["-descrizione"],
            },
        ),
        migrations.CreateModel(
            name="PrezzoProdotto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inserimento", models.DateField(default=datetime.date.today)),
                ("prezzo", models.DecimalField(decimal_places=3, max_digits=8)),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prezzi_prodotti_chimici",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fk_prodottochimico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prezzo",
                        to="chem_man.prodottochimico",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_inserimento"],
            },
        ),
    ]
