# Generated by Django 4.2.1 on 2023-07-01 15:20

import chem_man.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chem_man", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchedaTecnica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "documento",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=chem_man.models.schedatecnica_upload_path,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "fk_prodottochimico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schede_tecniche",
                        to="chem_man.prodottochimico",
                    ),
                ),
            ],
        ),
    ]
