# Generated by Django 4.2.1 on 2023-07-03 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chem_man', '0003_schedatecnica_data_inserimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='SostanzaSVHC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=500)),
                ('data_inclusione', models.DateField()),
                ('num_cas', models.CharField(blank=True, max_length=20, null=True)),
                ('num_ec', models.CharField(blank=True, max_length=20, null=True)),
                ('num_reach', models.CharField(blank=True, max_length=20, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sostanze_svhc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['descrizione'],
            },
        ),
        migrations.CreateModel(
            name='Sostanza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=500)),
                ('num_cas', models.CharField(blank=True, max_length=20, null=True)),
                ('num_ec', models.CharField(blank=True, max_length=20, null=True)),
                ('num_reach', models.CharField(blank=True, max_length=20, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sostanze', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['descrizione'],
            },
        ),
        migrations.CreateModel(
            name='PrecautionaryStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=20)),
                ('descrizione', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precautionary_statement', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HazardStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard_statement', models.CharField(max_length=20)),
                ('descrizione', models.CharField(blank=True, max_length=100, null=True)),
                ('hazard_category', models.CharField(blank=True, choices=[('Pericoli Fisici', 'Pericoli Fisici'), ('Pericoli per la Salute', 'Pericoli per la Salute'), ("Pericoli per l'Ambiente", "Pericoli per l'Ambiente"), ('Pericoli Supplementari', 'Pericoli Supplementari')], max_length=50, null=True)),
                ('is_dangerous', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hazard_statement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['hazard_statement'],
            },
        ),
    ]
