# Generated by Django 4.2.1 on 2023-07-07 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chem_man', '0004_sostanzasvhc_sostanza_precautionarystatement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimboloGHS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=10)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('symbol_image', models.ImageField(blank=True, null=True, upload_to='static/ghs_symbols/')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simbolo_ghs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
