# Generated by Django 4.2.1 on 2023-07-12 14:13

import chem_man.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chem_man', '0005_simbologhs'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedaSicurezza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_revisione', models.DateField()),
                ('is_reach', models.BooleanField(default=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to=chem_man.models.schedasicurezza_upload_path)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sds', to=settings.AUTH_USER_MODEL)),
                ('fk_prodottochimico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sds', to='chem_man.prodottochimico')),
            ],
            options={
                'ordering': ['-data_revisione'],
            },
        ),
        migrations.CreateModel(
            name='SimboloGHS_SDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simbolo_ghs_sds', to=settings.AUTH_USER_MODEL)),
                ('fk_sds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simbolo_ghs_sds', to='chem_man.schedasicurezza')),
                ('fk_simbolo_ghs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simbolo_ghs_sds', to='chem_man.simbologhs')),
            ],
        ),
        migrations.CreateModel(
            name='PrecautionaryStatement_SDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precautionary_statement_sds', to=settings.AUTH_USER_MODEL)),
                ('fk_precautionary_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precautionary_statement_sds', to='chem_man.precautionarystatement')),
                ('fk_sds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precautionary_statement_sds', to='chem_man.schedasicurezza')),
            ],
        ),
        migrations.CreateModel(
            name='HazardStatement_SDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hazard_statement_sds', to=settings.AUTH_USER_MODEL)),
                ('fk_hazard_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hazard_statement_sds', to='chem_man.hazardstatement')),
                ('fk_sds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hazard_statement_sds', to='chem_man.schedasicurezza')),
            ],
        ),
    ]
