# Generated by Django 4.2.1 on 2023-07-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chem_man", "0009_prodottochimico_fk_imballaggio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordineprodottochimico",
            name="is_conforme",
            field=models.BooleanField(default=False),
        ),
    ]
