# Generated by Django 4.2.1 on 2023-07-25 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0007_alter_fornitore_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chem_man', '0012_alter_dettaglioordineprodottochimico_fk_prodotto_chimico'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquistoProdottoChimico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=15)),
                ('data_documento', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acquisto_prodotti_chimici', to=settings.AUTH_USER_MODEL)),
                ('fk_fornitore', models.ForeignKey(limit_choices_to={'categoria': 'prodotti chimici'}, on_delete=django.db.models.deletion.CASCADE, related_name='acquisto_prodotti_chimici', to='anagrafiche.fornitore')),
            ],
            options={
                'ordering': ['-data_documento'],
            },
        ),
        migrations.CreateModel(
            name='DettaglioAcquistoProdottoChimico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_misura', models.CharField(max_length=3)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dettagli_acquisto', to=settings.AUTH_USER_MODEL)),
                ('fk_acquisto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettagli_acquisto', to='chem_man.acquistoprodottochimico')),
                ('fk_prodotto_chimico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chem_man.prodottochimico')),
            ],
        ),
    ]
