# Generated by Django 4.2.1 on 2023-07-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chem_man", "0014_dettaglioacquistoprodottochimico_solvente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dettaglioacquistoprodottochimico",
            name="prezzo",
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
