# Generated by Django 4.2.1 on 2024-02-20 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0029_remove_facilityauthorization_created_by_and_more'),
        ('chem_man', '0021_alter_sostanzasvhc_num_ec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodottochimico',
            name='fk_fornitore',
            field=models.ForeignKey(limit_choices_to=models.Q(('categoria', 'prodotti chimici'), ('categoria', 'nessuna'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='prodotto_chimico', to='anagrafiche.fornitore'),
        ),
    ]
