# Generated by Django 4.2.1 on 2023-10-25 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoEmissione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camino_numero', models.CharField(max_length=50)),
                ('origine', models.CharField(help_text='P.E.: cabina rifinizione pelli, depolveratore linea...', max_length=50)),
                ('quota', models.CharField(blank=True, max_length=50, null=True)),
                ('portata', models.DecimalField(blank=True, decimal_places=2, help_text='Nm3/h', max_digits=9, null=True)),
                ('parametri', models.CharField(blank=True, help_text='P.E.: polveri', max_length=50, null=True)),
                ('limite_conc', models.DecimalField(blank=True, decimal_places=2, help_text='mg/Nm3', max_digits=5, null=True)),
                ('limite_flusso', models.DecimalField(blank=True, decimal_places=2, help_text='g/h', max_digits=8, null=True)),
                ('tipo_abbattimento', models.CharField(blank=True, help_text='P.E.: Ad umido, filtri a secco...', max_length=50, null=True)),
                ('soggetto_controllo', models.BooleanField(default=False)),
                ('autorizzazione', models.CharField(blank=True, max_length=100, null=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punto_emissione', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroControlloAnalitico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_prelievo', models.DateField()),
                ('portata_risc', models.DecimalField(blank=True, decimal_places=2, help_text='Nm3/h', max_digits=9, null=True)),
                ('conc_risc', models.DecimalField(blank=True, decimal_places=2, help_text='mg/Nm3', max_digits=5, null=True)),
                ('flusso_risc', models.DecimalField(blank=True, decimal_places=2, help_text='g/h', max_digits=8, null=True)),
                ('certificato_numero', models.CharField(blank=True, max_length=50, null=True)),
                ('certificato', models.FileField(blank=True, null=True, upload_to='analisi_fumi/')),
                ('fk_punto_emissione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registro_controllo_analitico', to='air_emissions.puntoemissione')),
            ],
        ),
    ]
