# Generated by Django 4.2.1 on 2023-10-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_emissions', '0002_registrocontrolloanalitico_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoemissione',
            name='descrizione_origine',
            field=models.TextField(blank=True, help_text="Aggiungi una breve descrizione dell'origine.", null=True),
        ),
    ]
