# Generated by Django 4.2.1 on 2023-06-01 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import human_resources.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("anagrafiche", "0006_alter_transfervalue_options"),
        ("human_resources", "0002_humanresource_country_alter_humanresource_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaFormazione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descrizione", models.CharField(max_length=50)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="area_formazione",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CorsoFormazione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descrizione", models.CharField(max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="corso_formazione",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fk_areaformazione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="human_resources.areaformazione",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistroFormazione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_formazione", models.DateField()),
                ("ore", models.IntegerField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registro_formazione",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fk_corso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="human_resources.corsoformazione",
                    ),
                ),
                (
                    "fk_fornitore",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="anagrafiche.fornitore",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_formazione"],
            },
        ),
        migrations.CreateModel(
            name="DettaglioRegistroFormazione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "certificato",
                    models.FileField(
                        upload_to=human_resources.models.corso_directory_path
                    ),
                ),
                (
                    "presenza",
                    models.CharField(
                        choices=[("presente", "Presente"), ("assente", "Assente")],
                        max_length=10,
                    ),
                ),
                ("efficace", models.BooleanField(default=True)),
                (
                    "fk_hr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="human_resources.humanresource",
                    ),
                ),
                (
                    "fk_registro_formazione",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="anagrafiche.fornitore",
                    ),
                ),
            ],
        ),
    ]
