# Generated by Django 4.2.1 on 2023-06-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human_resources", "0012_valutazioneoperatore_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="humanresource",
            name="data_nascita",
            field=models.DateField(blank=True, null=True),
        ),
    ]
