# Generated by Django 4.2.1 on 2023-06-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0013_humanresource_data_nascita'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroorelavoro',
            options={'ordering': ['-entry_year', '-entry_month']},
        ),
        migrations.AlterField(
            model_name='registroorelavoro',
            name='entry_month',
            field=models.IntegerField(choices=[(1, 'Gennaio'), (2, 'Febbraio'), (3, 'Marzo'), (4, 'Aprile'), (5, 'Maggio'), (6, 'Giugno'), (7, 'Luglio'), (8, 'Agosto'), (9, 'Settembre'), (10, 'Ottobre'), (11, 'Novembre'), (12, 'Dicembre')], default=6),
        ),
    ]
