# Generated by Django 4.2.1 on 2023-07-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("human_resources", "0015_alter_registroorelavoro_entry_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="humanresource",
            name="contratto",
            field=models.CharField(
                blank=True,
                choices=[
                    ("determinato", "Determinato"),
                    ("indeterminato", "Indeterminato"),
                ],
                max_length=13,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="humanresource",
            name="orario",
            field=models.CharField(
                blank=True,
                choices=[("part_time", "Part-time"), ("full_time", "Full-time")],
                max_length=9,
                null=True,
            ),
        ),
    ]
