# Generated by Django 4.2.1 on 2023-09-20 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0019_safety_role_hr_safety'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='safety_role',
            options={'ordering': ['descrizione']},
        ),
    ]
