# Generated by Django 4.2.1 on 2023-12-11 14:04

from django.db import migrations, models
import human_resources.models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0023_alter_areaformazione_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dettaglioregistroformazione',
            name='certificato',
            field=models.FileField(blank=True, null=True, upload_to=human_resources.models.corso_directory_path),
        ),
        migrations.AlterField(
            model_name='registroorelavoro',
            name='entry_month',
            field=models.IntegerField(choices=[(1, 'Gennaio'), (2, 'Febbraio'), (3, 'Marzo'), (4, 'Aprile'), (5, 'Maggio'), (6, 'Giugno'), (7, 'Luglio'), (8, 'Agosto'), (9, 'Settembre'), (10, 'Ottobre'), (11, 'Novembre'), (12, 'Dicembre')], default=12),
        ),
    ]
