# Generated by Django 4.2.1 on 2026-02-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0039_valutazioneoperatore_created_by_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='hr_safety',
            index=models.Index(fields=['fk_hr', 'fk_safety_role'], name='idx_hr_safety_lookup'),
        ),
    ]
