# Generated by Django 4.2.1 on 2023-06-20 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autorizzazioni', '0003_parametroautorizzazione'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoApplicazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(help_text='descrizione', max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campo_applicazione', to=settings.AUTH_USER_MODEL)),
                ('fk_autorizzazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autorizzazioni.autorizzazione')),
            ],
            options={
                'ordering': ['descrizione'],
            },
        ),
        migrations.CreateModel(
            name='DettaglioCampoApplicazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('um', models.CharField(blank=True, help_text='unità_misura', max_length=10, null=True)),
                ('limite', models.DecimalField(decimal_places=3, max_digits=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dettaglio_campo_applicazione', to=settings.AUTH_USER_MODEL)),
                ('fk_campoapplicazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autorizzazioni.campoapplicazione')),
                ('fk_parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autorizzazioni.parametroautorizzazione')),
            ],
        ),
    ]
