# Generated by Django 4.2.1 on 2023-06-28 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nonconformity', '0002_alter_rapportonc_causa_radice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportoAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_rapporto_audit', models.PositiveIntegerField(editable=False)),
                ('data_rapporto_audit', models.DateField()),
                ('norme_riferimento', models.TextField(blank=True, null=True)),
                ('auditor', models.TextField(blank=True, null=True)),
                ('risultato', models.TextField(blank=True, null=True)),
                ('data_controllo', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapporto_audit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_rapporto_audit'],
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=100)),
                ('classe_processo', models.CharField(choices=[('Direzionale', 'Direzionale'), ('Principale', 'Principale'), ('Supporto', 'Supporto')], max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processo_audit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rapportonc',
            name='fk_rapportoaudit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nonconformity.rapportoaudit'),
        ),
    ]
