# Generated by Django 4.2.1 on 2023-05-22 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fornitore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ragionesociale", models.CharField(max_length=50)),
                ("indirizzo", models.CharField(blank=True, max_length=100, null=True)),
                ("cap", models.CharField(blank=True, max_length=50, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("provincia", models.CharField(blank=True, max_length=50, null=True)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("nessuna", "Manca categoria"),
                            ("pelli", "Pelli"),
                            ("prodotti chimici", "Prodotti Chimici"),
                            ("lavorazioni esterne", "Lavorazioni Esterne"),
                            ("servizi", "Servizi"),
                        ],
                        default="nessuna",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fornitori",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["ragionesociale"],
            },
        ),
    ]
