# Generated by Django 4.2.1 on 2023-05-26 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0003_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornitore',
            name='is_lwg',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LwgFornitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lwg_urn', models.CharField(max_length=50)),
                ('lwg_score', models.CharField(blank=True, max_length=50, null=True)),
                ('lwg_range', models.CharField(blank=True, max_length=100, null=True)),
                ('lwg_date', models.DateField(blank=True, null=True)),
                ('lwg_expiry', models.DateField(blank=True, null=True)),
                ('fk_fornitore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anagrafiche.fornitore')),
            ],
        ),
    ]
