# Generated by Django 4.2.1 on 2023-07-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0009_rename_fornitore_lavorazioni_esterne_fornitorelavorazioniesterne_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fornitoreprodottichimici',
            old_name='prova',
            new_name='id_zdhc',
        ),
        migrations.RemoveField(
            model_name='fornitorelavorazioniesterne',
            name='prova',
        ),
        migrations.AddField(
            model_name='fornitorelavorazioniesterne',
            name='audit',
            field=models.CharField(choices=[('not_audited', 'Nessun Audit'), ('leather_manufacturer_audit_protocol', 'Leather Manufacturer Audit Protocol'), ('subcontractor_audit_protocol', 'Subcontractor Audit Protocol'), ('mini_audit_protocol', 'Mini-Audit Protocol')], default='not_audited', max_length=50),
        ),
    ]
