# Generated by Django 4.2.1 on 2023-10-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0019_fornitoremanutenzioni'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornitore',
            name='e_mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
