# Generated by Django 4.2.1 on 2023-12-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0027_lwgfornitore_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xrtransfervaluelwgfornitore',
            name='quantity',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
    ]
