# Generated by Django 4.2.1 on 2024-03-05 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0029_remove_facilityauthorization_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Macello',
            fields=[
                ('fornitore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='anagrafiche.fornitore')),
                ('is_group', models.BooleanField(default=False)),
            ],
            bases=('anagrafiche.fornitore',),
        ),
    ]
