# Generated by Django 4.2.1 on 2024-03-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anagrafiche", "0030_macello"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fornitore",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("nessuna", "Manca categoria"),
                    ("pelli", "Pelli"),
                    ("macello", "Macello"),
                    ("prodotti chimici", "Prodotti Chimici"),
                    ("lavorazioni esterne", "Lavorazioni Esterne"),
                    ("servizi", "Servizi"),
                    ("manutenzioni", "Manutenzioni"),
                    ("rifiuti", "Rifiuti"),
                ],
                default="nessuna",
                max_length=50,
            ),
        ),
    ]
