# Generated by Django 4.2.1 on 2024-10-04 14:05

import anagrafiche.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0031_alter_fornitore_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='XrDocumentiTrasportatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(upload_to=anagrafiche.models.trasportatore_documenti_upload_to)),
                ('data_scadenza', models.DateField(blank=True, null=True)),
                ('fornitore_rifiuti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenti_trasportatore', to='anagrafiche.fornitorerifiuti')),
            ],
            options={
                'verbose_name_plural': 'Documenti Trasportatore',
            },
        ),
        migrations.CreateModel(
            name='XrDocumentiSmaltitore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(upload_to=anagrafiche.models.smaltitore_documenti_upload_to)),
                ('data_scadenza', models.DateField(blank=True, null=True)),
                ('fornitore_rifiuti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenti_smaltitore', to='anagrafiche.fornitorerifiuti')),
            ],
            options={
                'verbose_name_plural': 'Documenti Smaltitore',
            },
        ),
        migrations.CreateModel(
            name='XrDocumentiGestore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(upload_to=anagrafiche.models.gestore_documenti_upload_to)),
                ('data_scadenza', models.DateField(blank=True, null=True)),
                ('fornitore_rifiuti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenti_gestore', to='anagrafiche.fornitorerifiuti')),
            ],
            options={
                'verbose_name_plural': 'Documenti Gestore',
            },
        ),
    ]
