# Generated by Django 4.2.1 on 2024-10-08 15:02

import anagrafiche.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0035_xrdocumentigestore_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornitorerifiuti',
            name='id',
        ),
        migrations.AlterField(
            model_name='fornitorerifiuti',
            name='fornitore_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='fornitore_ptr_rifiuti', serialize=False, to='anagrafiche.fornitore'),
        ),
        migrations.AlterField(
            model_name='xrdocumentigestore',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to=anagrafiche.models.gestore_documenti_upload_to),
        ),
    ]
