# Generated by Django 4.2.1 on 2025-03-05 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acquistopelli', '0009_lotto_fk_macello'),
        ('anagrafiche', '0042_remove_fornitorelavorazioniesterne_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Macello',
            new_name='FornitoreMacello',
        ),
    ]
