# Generated by Django 4.2.1 on 2025-03-05 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0043_rename_macello_fornitoremacello'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornitoremacello',
            name='fornitore_ptr',
        ),
        migrations.AddField(
            model_name='fornitoremacello',
            name='fornitore_ptr_macello',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='anagrafiche.fornitore'),
            preserve_default=False,
        ),
    ]
