# Generated by Django 4.2.1 on 2025-03-05 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0044_remove_fornitoremacello_fornitore_ptr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fornitoremacello',
            old_name='fornitore_ptr_macello',
            new_name='fornitore_ptr',
        ),
    ]
