# Generated by Django 4.2.1 on 2025-06-17 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0045_rename_fornitore_ptr_macello_fornitoremacello_fornitore_ptr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xrdocumentigestore',
            name='fornitore_rifiuti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenti_gestore', to='anagrafiche.fornitore'),
        ),
        migrations.AlterField(
            model_name='xrdocumentismaltitore',
            name='fornitore_rifiuti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenti_smaltitore', to='anagrafiche.fornitore'),
        ),
        migrations.AlterField(
            model_name='xrdocumentitrasportatore',
            name='fornitore_rifiuti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documenti_trasportatore', to='anagrafiche.fornitore'),
        ),
    ]
