# Generated by Django 4.2.1 on 2025-06-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0047_remove_fornitoremacello_fornitore_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornitore',
            name='audit',
            field=models.CharField(blank=True, choices=[('not_audited', 'Nessun Audit'), ('leather_manufacturer_audit_protocol', 'Leather Manufacturer Audit Protocol'), ('subcontractor_audit_protocol', 'Subcontractor Audit Protocol'), ('mini_audit_protocol', 'Mini-Audit Protocol')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fornitore',
            name='id_zdhc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fornitore',
            name='is_lwg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fornitore',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fornitore',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fornitore',
            name='manutenzione_note',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fornitore',
            name='tipo_fornitore',
            field=models.CharField(blank=True, choices=[('macello', 'Macello'), ('commerciante', 'Commerciante'), ('altro', 'Altro')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fornitore',
            name='urn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
