# Generated by Django 4.2.1 on 2023-06-22 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionerifiuti', '0002_alter_codicecer_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoRifiuti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimento', models.DateField()),
                ('car_scar', models.CharField(choices=[('carico', 'Carico'), ('scarico', 'Scarico')], max_length=7)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimento_rifiuti', to=settings.AUTH_USER_MODEL)),
                ('fk_codicecer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimento_rifiuti', to='gestionerifiuti.codicecer')),
                ('fk_smaltrec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimento_rifiuti', to='gestionerifiuti.codicesmaltrec')),
            ],
            options={
                'verbose_name_plural': 'Movimenti Rifiuti',
                'ordering': ['-data_movimento'],
            },
        ),
    ]
