# Generated by Django 4.2.1 on 2023-06-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionerifiuti", "0004_alter_codicesmaltrec_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codicecer",
            name="descrizione",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
