# Generated by Django 4.2.1 on 2023-07-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionerifiuti", "0005_alter_codicecer_descrizione"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codicesmaltrec",
            name="descrizione",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
