# Generated by Django 4.2.1 on 2023-06-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articoli", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faselavoro",
            name="um",
            field=models.CharField(
                blank=True,
                choices=[("mq", "Mq."), ("Nr.", "Nr."), ("Kg.", "Kg.")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="articolo",
            name="scheda_tecnica",
            field=models.FileField(
                blank=True, null=True, upload_to="schede_tecniche_articoli/"
            ),
        ),
    ]
