# Generated by Django 4.2.1 on 2023-06-27 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "acquistopelli",
            "0005_alter_lotto_fk_fornitore_alter_lotto_fk_tipoanimale_and_more",
        ),
        ("articoli", "0003_procedura_dettaglioprocedura"),
    ]

    operations = [
        migrations.AddField(
            model_name="articolo",
            name="fk_tipoanimale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articolo",
                to="acquistopelli.tipoanimale",
            ),
        ),
        migrations.AddField(
            model_name="articolo",
            name="fk_tipogrezzo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articolo",
                to="acquistopelli.tipogrezzo",
            ),
        ),
        migrations.AddField(
            model_name="articolo",
            name="industries_served",
            field=models.CharField(
                blank=True,
                choices=[
                    ("apparel/clothing", "Apparel/clothing"),
                    ("automotive", "Automotive"),
                    ("contract", "Contract"),
                    ("footwear", "Footwear"),
                    ("footwear (athletic)", "Footwear (Athletic)"),
                    ("leather goods", "Leather goods"),
                    ("upholstery", "Upholstery"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
