# Generated by Django 4.2.1 on 2023-10-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0005_elencotest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elencotest',
            name='norma_riferimento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
