# Generated by Django 4.2.1 on 2024-03-14 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0031_alter_fornitore_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articoli', '0015_alter_dettaglioprocedura_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaratteristicaProcedura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caratteristicaprocedura', to=settings.AUTH_USER_MODEL)),
                ('fk_dettaglio_fase_lavoro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caratteristicaprocedura', to='articoli.dettagliofaselavoro')),
                ('fk_dettaglio_procedura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caratteristicaprocedura', to='articoli.dettaglioprocedura')),
                ('fk_fornitore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caratteristicaprocedura', to='anagrafiche.fornitore')),
                ('fk_lavorazione_esterna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caratteristicaprocedura', to='articoli.lavorazioneesterna')),
            ],
        ),
    ]
