# Generated by Django 4.2.1 on 2024-03-28 10:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anagrafiche', '0031_alter_fornitore_categoria'),
        ('articoli', '0018_caratteristicaprocedura_numero_riga'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListinoTerzista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listino_terzista', to=settings.AUTH_USER_MODEL)),
                ('fk_fornitore_lavorazione_esterna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anagrafiche.fornitorelavorazioniesterne')),
                ('fk_lavorazione_esterna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articoli.lavorazioneesterna')),
            ],
        ),
        migrations.CreateModel(
            name='PrezzoListino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inserimento', models.DateField(default=datetime.date.today)),
                ('prezzo', models.DecimalField(decimal_places=3, max_digits=8)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prezzo_listino', to=settings.AUTH_USER_MODEL)),
                ('fk_listino_terzista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prezzo_listino', to='articoli.listinoterzista')),
            ],
            options={
                'ordering': ['-data_inserimento'],
            },
        ),
    ]
