# Generated by Django 4.2.1 on 2024-03-28 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0031_alter_fornitore_categoria'),
        ('articoli', '0019_listinoterzista_prezzolistino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listinoterzista',
            name='fk_fornitore_lavorazione_esterna',
        ),
        migrations.AddField(
            model_name='listinoterzista',
            name='fk_fornitore',
            field=models.ForeignKey(default=200, on_delete=django.db.models.deletion.CASCADE, to='anagrafiche.fornitore'),
            preserve_default=False,
        ),
    ]
