# Generated by Django 4.2.1 on 2024-03-30 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("anagrafiche", "0031_alter_fornitore_categoria"),
        ("articoli", "0021_alter_prezzolistino_fk_listino_terzista"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListinoCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prezzo", models.DecimalField(decimal_places=3, max_digits=8)),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listino_cliente",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fk_articolo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listino_cliente",
                        to="articoli.articolo",
                    ),
                ),
                (
                    "fk_cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listino_cliente",
                        to="anagrafiche.cliente",
                    ),
                ),
            ],
        ),
    ]
