# Generated by Django 4.2.1 on 2023-09-13 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estintore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_estinguente', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=100)),
                ('peso', models.CharField(max_length=100)),
                ('matricola', models.CharField(max_length=100)),
                ('anno', models.CharField(max_length=4)),
                ('ubicazione', models.CharField(max_length=200)),
                ('data_dismissione', models.DateField(blank=True, null=True)),
                ('numero_posizione', models.IntegerField()),
                ('scadenza_revisione', models.DateField()),
                ('scadenza_collaudo', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estintore', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['numero_posizione'],
            },
        ),
        migrations.CreateModel(
            name='ControlloPeriodicoEstintore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_controllo', models.CharField(choices=[('interno', 'Interno'), ('programmato', 'Programmato (Ditta Esterna)')], max_length=30)),
                ('scadenza', models.DateField()),
                ('eseguita', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controllo_periodico_estintore', to=settings.AUTH_USER_MODEL)),
                ('fk_estintore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controllo_periodico_estintore', to='antincendio.estintore')),
            ],
            options={
                'ordering': ['-scadenza'],
            },
        ),
    ]
