# Generated by Django 4.2.1 on 2023-09-15 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('antincendio', '0002_idrante'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortaUscita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_posizione', models.IntegerField()),
                ('tipo_porta', models.CharField(choices=[('portone scorrevole', 'Portone scorrevole'), ('normale', 'Normale'), ('tagliafuoco', 'Tagliafuoco'), ('uscita di sicurezza', 'Uscita di sicurezza')], max_length=35)),
                ('marcatura_ce', models.BooleanField(default=False)),
                ('maniglia', models.CharField(choices=[('maniglione antipanico', 'Maniglione Antipanico'), ('maniglia', 'Maniglia')], max_length=35)),
                ('anta', models.CharField(choices=[('anta normale', 'Anta normale'), ('due ante', 'Due ante'), ('portone scorrevole', 'Portone scorrevole')], max_length=35)),
                ('matricola', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicazione', models.CharField(blank=True, max_length=200, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='porta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['numero_posizione'],
            },
        ),
    ]
