# Generated by Django 4.2.1 on 2023-09-18 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0018_alter_registroorelavoro_entry_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anagrafiche', '0019_fornitoremanutenzioni'),
        ('antincendio', '0004_attrezzaturaantincendio_impiantospegnimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroControlliAntincendio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interno_esterno', models.CharField(choices=[('interno', 'Interno'), ('esterno', 'Esterno')], max_length=35)),
                ('numero_intervento', models.CharField(blank=True, max_length=10, null=True)),
                ('data_intervento', models.DateField()),
                ('prossima_scadenza', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registro_controlli_antincendio', to=settings.AUTH_USER_MODEL)),
                ('fk_fornitore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registro_controlli_antincendio', to='anagrafiche.fornitore')),
                ('fk_operatore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registro_controlli_antincendio', to='human_resources.humanresource')),
            ],
        ),
        migrations.CreateModel(
            name='DettaglioRegistroPortaUscita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manutenzione_effettuata', models.BooleanField(default=False)),
                ('controllo_effettuato', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dettaglio_registro_porta_uscita', to=settings.AUTH_USER_MODEL)),
                ('fk_porta_uscita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettaglio_registro_porta_uscita', to='antincendio.portauscita')),
                ('fk_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettaglio_registro_porta_uscita', to='anagrafiche.fornitore')),
            ],
        ),
        migrations.CreateModel(
            name='DettaglioRegistroImpiangoSpegnimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manutenzione_effettuata', models.BooleanField(default=False)),
                ('controllo_effettuato', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dettaglio_registro_attrezzatura_antincendio', to=settings.AUTH_USER_MODEL)),
                ('fk_attrezzatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettaglio_registro_attrezzatura_antincendio', to='antincendio.attrezzaturaantincendio')),
                ('fk_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettaglio_registro_attrezzatura_antincendio', to='anagrafiche.fornitore')),
            ],
        ),
        migrations.CreateModel(
            name='DettaglioRegistroIdrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manutenzione_effettuata', models.BooleanField(default=False)),
                ('controllo_effettuato', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dettaglio_registro_idrante', to=settings.AUTH_USER_MODEL)),
                ('fk_idrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettaglio_registro_idrante', to='antincendio.idrante')),
                ('fk_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettaglio_registro_idrante', to='anagrafiche.fornitore')),
            ],
        ),
        migrations.CreateModel(
            name='DettaglioRegistroEstintore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manutenzione_effettuata', models.BooleanField(default=False)),
                ('controllo_effettuato', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dettaglio_registro_estintore', to=settings.AUTH_USER_MODEL)),
                ('fk_estintore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettaglio_registro_estintore', to='antincendio.estintore')),
                ('fk_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettaglio_registro_estintore', to='anagrafiche.fornitore')),
            ],
        ),
    ]
