# Generated by Django 4.2.1 on 2023-09-18 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anagrafiche', '0019_fornitoremanutenzioni'),
        ('antincendio', '0005_registrocontrolliantincendio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dettaglioregistroimpiangospegnimento',
            name='fk_attrezzatura',
        ),
        migrations.AddField(
            model_name='dettaglioregistroimpiangospegnimento',
            name='fk_impianto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dettaglio_registro_impianto_spegnimento', to='antincendio.impiantospegnimento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dettaglioregistroimpiangospegnimento',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dettaglio_registro_impianto_spegnimento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dettaglioregistroimpiangospegnimento',
            name='fk_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettaglio_registro_impianto_spegnimento', to='anagrafiche.fornitore'),
        ),
        migrations.CreateModel(
            name='DettaglioRegistroAttrezzaturaAntincendio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manutenzione_effettuata', models.BooleanField(default=False)),
                ('controllo_effettuato', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dettaglio_registro_attrezzatura_antincendio', to=settings.AUTH_USER_MODEL)),
                ('fk_attrezzatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettaglio_registro_attrezzatura_antincendio', to='antincendio.attrezzaturaantincendio')),
                ('fk_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettaglio_registro_attrezzatura_antincendio', to='anagrafiche.fornitore')),
            ],
        ),
    ]
