# Generated by Django 4.2.1 on 2023-11-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antincendio', '0007_attrezzaturaantincendio_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estintore',
            name='certificato_conf',
            field=models.FileField(blank=True, null=True, upload_to='extinguisher_conformity/'),
        ),
        migrations.AlterField(
            model_name='idrante',
            name='tipo_idrante',
            field=models.CharField(choices=[('idrante a parete', 'Idrante a Parete'), ('Idrante soprasuolo', 'Idrante soprasuolo'), ('Idrante a colonna soprasuolo', 'Idrante a colonna soprasuolo'), ('Gruppo fisso schiuma', 'Gruppo fisso schiuma'), ('Gruppo mobile schiuma', 'Gruppo mobile schiuma'), ('Attacco autopompa VVF', 'Attacco autopompa VVF'), ('Alimentazione acquedotto', 'Alimentazione acquedotto'), ('Alimentazione con pompe', 'Alimentazione con pompe'), ('Evacuatori di fumo', 'Evacuatori di fumo'), ('Naspo', 'Naspo')], max_length=35),
        ),
    ]
