# Generated by Django 4.2.1 on 2023-07-02 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chem_man", "0002_schedatecnica"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedatecnica",
            name="data_inserimento",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
