# Generated by Django 4.2.1 on 2023-07-14 14:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0007_alter_fornitore_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chem_man', '0007_sostanza_sds'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdineProdottoChimico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordine', models.IntegerField(default=None)),
                ('data_ordine', models.DateField(default=datetime.date.today)),
                ('data_consegna', models.DateField(blank=True, null=True)),
                ('is_conforme', models.BooleanField(default=True)),
                ('note_nc', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordine_prodotti_chimici', to=settings.AUTH_USER_MODEL)),
                ('fk_fornitore', models.ForeignKey(limit_choices_to={'categoria': 'prodotti chimici'}, on_delete=django.db.models.deletion.CASCADE, related_name='ordine_prodotti_chimici', to='anagrafiche.fornitore')),
            ],
            options={
                'ordering': ['-data_ordine'],
            },
        ),
        migrations.CreateModel(
            name='ImballaggioPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=50)),
                ('peso_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imballaggi_pc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DettaglioOrdineProdottoChimico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_misura', models.CharField(max_length=3)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dettagli_ordine', to=settings.AUTH_USER_MODEL)),
                ('fk_imballaggio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dettagli_ordine', to='chem_man.imballaggiopc')),
                ('fk_ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettagli_ordine', to='chem_man.ordineprodottochimico')),
                ('fk_prodotto_chimico', models.ForeignKey(limit_choices_to=models.Q(('fk_fornitore', models.F('fk_ordine__fk_fornitore'))), on_delete=django.db.models.deletion.CASCADE, to='chem_man.prodottochimico')),
            ],
        ),
    ]
