# Generated by Django 4.2.1 on 2023-07-15 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chem_man", "0008_ordineprodottochimico_imballaggiopc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prodottochimico",
            name="fk_imballaggio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prodotto_chimico",
                to="chem_man.imballaggiopc",
            ),
        ),
    ]
