# Generated by Django 4.2.1 on 2023-07-19 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chem_man', '0010_alter_ordineprodottochimico_is_conforme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dettaglioordineprodottochimico',
            name='fk_prodotto_chimico',
            field=models.ForeignKey(limit_choices_to=models.Q(('fk_ordine__fk_fornitore', models.F('fk_prodotto_chimico__fk_fornitore'))), on_delete=django.db.models.deletion.CASCADE, to='chem_man.prodottochimico'),
        ),
    ]
