# Generated by Django 4.2.1 on 2023-09-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chem_man", "0016_alter_hazardstatement_descrizione_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperazioneBagnato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descrizione", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="OperazioneRifinizione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descrizione", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="RicettaBagnato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
