# Generated by Django 4.2.1 on 2023-09-12 18:59

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("articoli", "0004_articolo_fk_tipoanimale_articolo_fk_tipogrezzo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "acquistopelli",
            "0005_alter_lotto_fk_fornitore_alter_lotto_fk_tipoanimale_and_more",
        ),
        ("chem_man", "0017_operazionebagnato_operazionerifinizione_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperazioneRicette",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descrizone", models.CharField(max_length=100)),
                (
                    "ward_ref",
                    models.CharField(
                        choices=[
                            ("Bagnato", "Bagnato"),
                            ("Rifinizione", "Rifinizione"),
                        ],
                        max_length=11,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RevisioneRicettaBagnato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_revisione", models.IntegerField(default=None)),
                ("data_revisione", models.DateField(default=datetime.date.today)),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisione_ricette_bagnato",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-data_revisione"],
            },
        ),
        migrations.CreateModel(
            name="RevisioneRicettaFondo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_revisione", models.IntegerField(default=None)),
                ("data_revisione", models.DateField(default=datetime.date.today)),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisione_ricette_fondo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-data_revisione"],
            },
        ),
        migrations.CreateModel(
            name="RicettaFondo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_ricetta", models.IntegerField(default=None)),
                ("data_ricetta", models.DateField(default=datetime.date.today)),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ricette_fondo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fk_colore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ricette_fondo",
                        to="articoli.colore",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_ricetta"],
            },
        ),
        migrations.CreateModel(
            name="RicettaRifinizione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="OperazioneBagnato",
        ),
        migrations.DeleteModel(
            name="OperazioneRifinizione",
        ),
        migrations.AlterModelOptions(
            name="ricettabagnato",
            options={"ordering": ["-data_ricetta"]},
        ),
        migrations.AddField(
            model_name="ricettabagnato",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ricettabagnato",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ricette_bagnato",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ricettabagnato",
            name="data_ricetta",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="ricettabagnato",
            name="fk_articolo",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ricette_bagnato",
                to="articoli.articolo",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ricettabagnato",
            name="fk_tipoanimale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ricette_bagnato",
                to="acquistopelli.tipoanimale",
            ),
        ),
        migrations.AddField(
            model_name="ricettabagnato",
            name="fk_tipogrezzo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ricette_bagnato",
                to="acquistopelli.tipogrezzo",
            ),
        ),
        migrations.AddField(
            model_name="ricettabagnato",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ricettabagnato",
            name="numero_ricetta",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="ricettafondo",
            name="fk_ricetta_bagnato",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ricette_fondo",
                to="chem_man.ricettabagnato",
            ),
        ),
        migrations.AddField(
            model_name="revisionericettafondo",
            name="fk_ricetta_fondo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revisione_ricette_fondo",
                to="chem_man.ricettafondo",
            ),
        ),
        migrations.AddField(
            model_name="revisionericettabagnato",
            name="fk_ricetta_bagnato",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revisione_ricette_bagnato",
                to="chem_man.ricettabagnato",
            ),
        ),
    ]
