# Generated by Django 4.2.1 on 2023-09-13 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chem_man", "0018_operazionericette_revisionericettabagnato_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OperazioneRicette",
        ),
        migrations.RemoveField(
            model_name="revisionericettabagnato",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="revisionericettabagnato",
            name="fk_ricetta_bagnato",
        ),
        migrations.RemoveField(
            model_name="revisionericettafondo",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="revisionericettafondo",
            name="fk_ricetta_fondo",
        ),
        migrations.RemoveField(
            model_name="ricettabagnato",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="ricettabagnato",
            name="fk_articolo",
        ),
        migrations.RemoveField(
            model_name="ricettabagnato",
            name="fk_tipoanimale",
        ),
        migrations.RemoveField(
            model_name="ricettabagnato",
            name="fk_tipogrezzo",
        ),
        migrations.RemoveField(
            model_name="ricettafondo",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="ricettafondo",
            name="fk_colore",
        ),
        migrations.RemoveField(
            model_name="ricettafondo",
            name="fk_ricetta_bagnato",
        ),
        migrations.DeleteModel(
            name="RicettaRifinizione",
        ),
        migrations.DeleteModel(
            name="RevisioneRicettaBagnato",
        ),
        migrations.DeleteModel(
            name="RevisioneRicettaFondo",
        ),
        migrations.DeleteModel(
            name="RicettaBagnato",
        ),
        migrations.DeleteModel(
            name="RicettaFondo",
        ),
    ]
