# Generated by Django 4.2.1 on 2023-11-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chem_man', '0020_alter_sostanzasvhc_descrizione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sostanzasvhc',
            name='num_ec',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
