# Generated by Django 4.2.1 on 2024-02-19 16:21

import chem_man.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chem_man', '0021_alter_sostanzasvhc_num_ec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodottochimico',
            name='descrizione',
            field=models.CharField(max_length=100, validators=[chem_man.models.no_duplicates]),
        ),
    ]
