# Generated by Django 4.2.1 on 2024-02-20 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chem_man', '0022_alter_prodottochimico_fk_fornitore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prodottochimico',
            options={'ordering': ['descrizione']},
        ),
    ]
