# Generated by Django 4.2.1 on 2023-06-22 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0007_alter_fornitore_created_by'),
        ('acquistopelli', '0004_alter_lotto_fk_tipoanimale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotto',
            name='fk_fornitore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotto', to='anagrafiche.fornitore'),
        ),
        migrations.AlterField(
            model_name='lotto',
            name='fk_tipoanimale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotto', to='acquistopelli.tipoanimale'),
        ),
        migrations.AlterField(
            model_name='lotto',
            name='fk_tipogrezzo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotto', to='acquistopelli.tipogrezzo'),
        ),
    ]
