# Generated by Django 4.2.1 on 2024-03-05 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0030_macello'),
        ('acquistopelli', '0008_alter_lotto_kg_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotto',
            name='fk_macello',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotto_macello', to='anagrafiche.macello'),
        ),
    ]
