# Generated by Django 4.2.1 on 2025-05-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquistopelli', '0009_lotto_fk_macello'),
    ]

    operations = [
        migrations.AddField(
            model_name='sceltalotto',
            name='data_termine',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sceltalotto',
            name='scelta_terminata',
            field=models.BooleanField(default=False),
        ),
    ]
