# Generated by Django 4.2.1 on 2025-06-17 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafiche', '0045_rename_fornitore_ptr_macello_fornitoremacello_fornitore_ptr'),
        ('acquistopelli', '0010_sceltalotto_data_termine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotto',
            name='fk_macello',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotto_macello', to='anagrafiche.fornitore'),
        ),
    ]
