# Generated by Django 4.2.1 on 2023-06-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquistopelli', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotto',
            name='prezzo_unitario',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='lotto',
            name='spese_accessorie',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
