# Generated by Django 4.2.1 on 2023-06-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquistopelli', '0002_alter_lotto_prezzo_unitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipogrezzo',
            name='descrizione',
            field=models.CharField(max_length=50),
        ),
    ]
