# Generated by Django 4.2.1 on 2023-06-22 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acquistopelli', '0003_alter_tipogrezzo_descrizione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotto',
            name='fk_tipoanimale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotti', to='acquistopelli.tipoanimale'),
        ),
    ]
