# Generated by Django 4.2.1 on 2024-02-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acquistopelli", "0007_lotto_kg_km"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lotto",
            name="kg_km",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Moltiplicare i kg. per i km percorsi per il calcolo della CO2",
                max_digits=10,
                null=True,
            ),
        ),
    ]
