# Generated by Django 4.2.1 on 2023-06-19 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manualeprocedure", "0004_alter_revisionemodulo_documento_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="revisioneprocedura",
            options={
                "get_latest_by": ["data_revisione"],
                "ordering": ["-data_revisione"],
            },
        ),
    ]
