# Generated by Django 4.2.1 on 2023-11-15 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air_emissions', '0003_puntoemissione_descrizione_origine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puntoemissione',
            options={'ordering': ['camino_numero'], 'verbose_name_plural': 'Punti di Emissione'},
        ),
        migrations.AlterModelOptions(
            name='registrocontrolloanalitico',
            options={'ordering': ['data_prelievo'], 'verbose_name_plural': 'Registri controlli analitici'},
        ),
    ]
