# Generated by Django 4.2.1 on 2024-01-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antincendio', '0009_alter_attrezzaturaantincendio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portauscita',
            name='certificato_conf',
            field=models.FileField(blank=True, null=True, upload_to='door_conformity/'),
        ),
    ]
