# Generated by Django 4.2.1 on 2025-05-21 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anagrafiche', '0045_rename_fornitore_ptr_macello_fornitoremacello_fornitore_ptr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdineCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordine', models.CharField(max_length=10)),
                ('data_ordine', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordine_cliente', to=settings.AUTH_USER_MODEL)),
                ('fk_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anagrafiche.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Ordine Cliente',
                'verbose_name_plural': 'Ordini Cliente',
                'ordering': ['-data_ordine'],
            },
        ),
        migrations.CreateModel(
            name='DettaglioOrdineCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dettaglio_ordine_cliente', to=settings.AUTH_USER_MODEL)),
                ('fk_ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettaglio_ordine', to='vendite.ordinecliente')),
            ],
            options={
                'verbose_name': 'Dettaglio Ordine',
                'verbose_name_plural': 'Dettaglio Ordini Cliente',
            },
        ),
    ]
