# Generated by Django 4.2.1 on 2025-05-21 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0022_listinocliente'),
        ('vendite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dettaglioordinecliente',
            name='fk_articolo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dettaglio_ordine', to='articoli.articolo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dettaglioordinecliente',
            name='fk_colore',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dettaglio_ordine', to='articoli.colore'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dettaglioordinecliente',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dettaglioordinecliente',
            name='riferimento',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='dettaglioordinecliente',
            name='um',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
