# Generated by Django 4.2.1 on 2025-05-21 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0022_listinocliente'),
        ('vendite', '0002_dettaglioordinecliente_fk_articolo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dettaglioordinecliente',
            name='fk_articolo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dettaglio_ordine', to='articoli.articolo', verbose_name='Articolo'),
        ),
        migrations.AlterField(
            model_name='dettaglioordinecliente',
            name='fk_colore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dettaglio_ordine', to='articoli.colore', verbose_name='Colore'),
        ),
    ]
