# Generated by Django 4.2.1 on 2023-06-11 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("articoli", "0002_faselavoro_um_alter_articolo_scheda_tecnica"),
    ]

    operations = [
        migrations.CreateModel(
            name="Procedura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nr_procedura", models.IntegerField()),
                ("data_procedura", models.DateField(default=django.utils.timezone.now)),
                ("nr_revisione", models.IntegerField()),
                ("data_revisione", models.DateField(default=django.utils.timezone.now)),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="procedure",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fk_articolo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articoli.articolo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DettaglioProcedura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dettaglioprocedura",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fk_faselavoro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articoli.faselavoro",
                    ),
                ),
                (
                    "fk_procedura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articoli.procedura",
                    ),
                ),
            ],
        ),
    ]
