# Generated by Django 4.2.1 on 2023-10-10 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articoli', '0006_alter_elencotest_norma_riferimento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elencotest',
            options={'ordering': ['descrizione'], 'verbose_name_plural': 'elenco test'},
        ),
        migrations.CreateModel(
            name='TestArticolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.CharField(blank=True, max_length=100, null=True)),
                ('interno_esterno', models.CharField(blank=True, choices=[('interno', 'Interno'), ('esterno', 'Esterno')], max_length=10, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_articolo', to=settings.AUTH_USER_MODEL)),
                ('fk_articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_articolo', to='articoli.articolo')),
                ('fk_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_articolo', to='articoli.elencotest')),
            ],
        ),
    ]
