# Generated by Django 4.2.1 on 2023-10-10 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0007_alter_elencotest_options_testarticolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='faselavoro',
            name='interno_esterno',
            field=models.CharField(blank=True, choices=[('interno', 'Interno'), ('esterno', 'Esterno')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='DettaglioFaseLavoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attibuto', models.CharField(max_length=100)),
                ('fk_fase_lavoro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articoli.faselavoro')),
            ],
        ),
    ]
