# Generated by Django 4.2.1 on 2023-10-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0009_dettagliofaselavoro_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dettagliofaselavoro',
            old_name='attibuto',
            new_name='attributo',
        ),
    ]
