# Generated by Django 4.2.1 on 2023-10-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articoli", "0010_rename_attibuto_dettagliofaselavoro_attributo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procedura",
            name="nr_procedura",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="procedura",
            name="nr_revisione",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
