# Generated by Django 4.2.1 on 2023-10-18 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anagrafiche', '0020_fornitore_e_mail'),
        ('articoli', '0012_dettaglioprocedura_numero_riga'),
    ]

    operations = [
        migrations.AddField(
            model_name='dettaglioprocedura',
            name='fk_fornitore',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='anagrafiche.fornitore'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LavorazioneEsterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=200)),
                ('codice', models.CharField(max_length=9)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lavorazione_esterna', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lavorazioni esterne',
                'ordering': ['descrizione'],
            },
        ),
    ]
