# Generated by Django 4.2.1 on 2024-03-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articoli', '0016_caratteristicaprocedura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caratteristicaprocedura',
            name='valore',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
