# Generated by Django 4.2.1 on 2024-03-28 15:09
# Modified: now a no-op since 0019 was fixed to create fk_fornitore directly

from django.db import migrations


class Migration(migrations.Migration):
    """
    Originally changed fk_fornitore_lavorazione_esterna -> fk_fornitore.
    Now a no-op: migration 0019 was fixed to create the correct schema directly.
    Kept for migration history compatibility with existing databases.
    """

    dependencies = [
        ('anagrafiche', '0031_alter_fornitore_categoria'),
        ('articoli', '0019_listinoterzista_prezzolistino'),
    ]

    operations = [
        # No-op: field change already done in 0019
    ]
