# Generated by Django 4.2.1 on 2024-03-28 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "articoli",
            "0020_remove_listinoterzista_fk_fornitore_lavorazione_esterna_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="prezzolistino",
            name="fk_listino_terzista",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prezzo",
                to="articoli.listinoterzista",
            ),
        ),
    ]
